---
title: "Usando el GBM"
author: "Maria Fernanda Gómez Flores"
date: "2026-09-10"
output: html_document
---

```{r}
library(quantmod)
library(moments)
library(tseries)
```


# Descargar datos reales
```{r}
# Descargar datos reales
ticker <- "GFNORTEO.MX"

getSymbols(ticker, src = "yahoo", from = "2015-01-01")
precio <- na.omit(Ad(get(ticker)))

```
#Precio, log del precio y los rendimientos

```{r}
log_precio <- log(precio)
simple_rend <- dailyReturn(precio, type="arithmetic")
log_rend <- dailyReturn(precio, type="log")
head(cbind(simple_rend,log_rend))

```

```{r}
plot(log_precio,main="Log Precio",col="blue")
plot(precio, main="Precio",col="red")
hist(precio,n=100,main="Histograma del precio",col="green")
plot(log_rend,n=100,main="Rendimiento",col="purple")
hist(log_rend,n=100,main="Histograma del Rendimiento",col="pink")


```

# Media y la volatilidad diaria
```{r}
r <-mean(log_rend)
R=mean(simple_rend)
sigma_log <- sd(log_rend)
mean_log <- r
sigma_log
mean_log
```
pregunta,la media del rendimiento logaritmico, es casi cero. ¿Podemos decir que es estadisticamente igual a cero?

$$Ho: \mu_r=0$$
$$Ha: \mu_r\neq 0$$

```{r}
t.test(as.numeric(log_rend), mu = 0, alternative = "two.sided")
```


Como el valor del pvalue es muy alto, eso implica que la probabilidad de rechazar Ho,cuandao es 